// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_h7gr3mkchsBS4nTPDltOVBAjn8y9vMk',
    appId: '1:717620846111:web:3040f323fb1b72e463bf2a',
    messagingSenderId: '717620846111',
    projectId: 'trawallet-1',
    authDomain: 'trawallet-1.firebaseapp.com',
    storageBucket: 'trawallet-1.firebasestorage.app',
    measurementId: 'G-S3J1YYN7YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUYrWpFBQVwLiATpJWXql4K2LQRRq6GeQ',
    appId: '1:717620846111:android:f065cb2ad8bcc84b63bf2a',
    messagingSenderId: '717620846111',
    projectId: 'trawallet-1',
    storageBucket: 'trawallet-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6MXGVinLN4yKOc8j46t697Q6EwLzLHrM',
    appId: '1:717620846111:ios:fbb5620adc31084c63bf2a',
    messagingSenderId: '717620846111',
    projectId: 'trawallet-1',
    storageBucket: 'trawallet-1.firebasestorage.app',
    androidClientId: '717620846111-g45kjgab8u7b5kp0n2k6mpmr7cihu8mv.apps.googleusercontent.com',
    iosClientId: '717620846111-c74nguvqh54mptdpi62bt3hb0phg6hnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.trawalletFinalVersion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6MXGVinLN4yKOc8j46t697Q6EwLzLHrM',
    appId: '1:717620846111:ios:fbb5620adc31084c63bf2a',
    messagingSenderId: '717620846111',
    projectId: 'trawallet-1',
    storageBucket: 'trawallet-1.firebasestorage.app',
    androidClientId: '717620846111-g45kjgab8u7b5kp0n2k6mpmr7cihu8mv.apps.googleusercontent.com',
    iosClientId: '717620846111-c74nguvqh54mptdpi62bt3hb0phg6hnu.apps.googleusercontent.com',
    iosBundleId: 'com.example.trawalletFinalVersion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_h7gr3mkchsBS4nTPDltOVBAjn8y9vMk',
    appId: '1:717620846111:web:c8b58cf92d85a0cf63bf2a',
    messagingSenderId: '717620846111',
    projectId: 'trawallet-1',
    authDomain: 'trawallet-1.firebaseapp.com',
    storageBucket: 'trawallet-1.firebasestorage.app',
    measurementId: 'G-C79B4CY32J',
  );
}
